services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shentcs_app
    volumes:
      - ./src:/var/www/html       # ← mount host/src ↔ container/var/www/html
    networks:
      - laravel
    ports:
      - "9000:9000" 

  web:
    image: nginx:1.25-alpine
    container_name: shentcs_nginx_server
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html       # ← nginx also sees the same code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mariadb:10.9
    container_name: shentcs_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel
    ports:
      - "3306:3306"    # MariaDB’s port

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: shentcs_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass   # or your root password
    ports:
      - "8081:80"
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data:
